config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations,except: [:new, :create]
  resources :tags


  root 'homes#index'
  get 'braintree/new'
  post 'braintree/checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
mount_uploaders :listing_image, ListingImageUploader
	validates :home_type,
            :listing_type,
            :accommodate,
            :bedroom,
            :bathroom,
            :summary,
            :address,
            :price,
            :city,
            presence: true

  # geocoded_by :address geocode gem to be added here

	validates :summary, length: { maximum: 500 }
	validates :address, length: { maximum: 50 }

	belongs_to :user
	has_many :reservation
	has_many :listing_tags
  has_many :tags, through: :listing_tags

  def self.home_types
  	[
  		["Shared Room","Shared Room"],
  		["Private Room","Private Room"], 
  		["Entire Home/Apt","Entire Home/Apt"]
  	] 
 	end

 	def self.listing_types
  	[
  		["Apartment","Apartment"],
  		["House","House"], 
  	] 
	end 

	 	def self.accommodate
  	[
  		["1","1"],
  		["2","2"], 
  		["3","3"],
  		["4","4"],
  		["5","5"],
  		["6","6"],
  		["7","7"],
  		["8","8"],
  		["9","9"],
  		["10","10"],
  		["11","11"],
  		["12","12"],
  		["13","13"],
  		["14","14"],
  		["15","15"],
  		["16","16"],
  	] 
	end 

	 	def self.bedroom
  	[
  		["1","1"],
  		["2","2"], 
  		["3","3"],
  		["4","4"],
  		["5","5"],
  		["6","6"],
  		["7","7"],
  		["8","8"],
  		["9","9"],
  		["10","10"],
  	] 
	end 

	 	def self.bathroom
  	[
  		["1","1"],
  		["2","2"], 
  		["3","3"],
  		["4","4"],
  		["5","5"],
  		["6","6"],
  		["7","7"],
  		["8","8"],
  	] 
	end 

  def self.city
    [
      ["Vancouver","Vancouver"],
      ["Kuala Lumpur","Kuala Lumpur"], 
    ] 
  end

  def self.search(search)
  where("city ILIKE ?", "%#{city}%") 
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
skip_before_filter :verify_authenticity_token, :only => :create
#shows all listings page

	def index
	  if params[:city]
	    @searchlistings = Listing.where(city: params[:city]).paginate(page: params[:page], per_page: 10)
	  else
	    @searchlistings = Listing.all.paginate(page: params[:page], per_page: 10)
	  end
	end


#renders page to create new listing (form on page)
	def new
		@listing = Listing.new
	end 

#method which actually creates the new listing 

	def create
	@new_listing = current_user.listings.new(listing_params)
		  if @new_listing.save
		  @notice = 'listing created'
		  else
		  @notice = 'listing creation FAILED'
		  end
		redirect_to new_listing_path, :notice => @notice
	end
	

#page where user clicked on single listing (id)
	def show
		@single_listing = Listing.find_by(id: params[:id])
	end

#delete single listing within show page
	def destroy
		@single_listing = Listing.find_by(id: params[:id]) 
		if @single_listing.destroy
			redirect_to listings_path, notice: 'Listing was successfully deleted.'
		end
	end

#update single listing within show page
	def edit
		@listing = Listing.find_by(id: params[:id]) 
	end

	def update
	@updated_listing = current_user.listings.find_by(id: params[:id])
	respond_to do |format|
		  if @updated_listing.update(listing_params)
			format.html { redirect_to listing_path(@updated_listing),
										notice: 'Listing was successfully updated!'
									}
			else
			format.js {  }
			end
		end 
	end 

	private
	def listing_params
		params.require(:listing).permit(:home_type,
																		:listing_type,
																		:accommodate,
																	  :bedroom,
																	  :bathroom,
																	  :summary,
																	  :address,
																	  :price,
																	  :city,
																	  {listing_image: []})
	end 
end 

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Back to all listings", listings_path %>
          </button>
         
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Home", root_path %>
          </button>
          </li>
        </ul>
      </div>
   </div>
  </nav>




<div class="row">
  <div class="col-sm-4"></div> <!-- empty div -->

<!-- there must be a better way to add buffer in between elements than doing top5 class on each indiv. button -->

  <div class="col-sm-4 well text-center top 5">
    <h1 class = "title"> Create New Listing </h1>

    <p class = "buffer5">
      <%= form.label :home_type %>
      <%= form.select :home_type, Listing.home_types, type: 'Home Type' %> 
    </p><br>

  	<p class = "buffer5">
      <%= form.label :listing_type %>
      <%= form.select :listing_type, Listing.listing_types, type: 'Listing Type' %>
    </p><br>

    <p class = "buffer5">
      <%= form.label :accommodate %>
      <%= form.select :accommodate, Listing.accommodate, type: 'Accomodates' %>
    </p><br>

    <p class = "buffer5">
      <%= form.label :bedroom %>
      <%= form.select :bedroom, Listing.bedroom, type: 'Bedrooms' %>  
    </p><br>

    <p class = "buffer5">
      <%= form.label :bathroom %>
      <%= form.select :bathroom, Listing.bathroom, type: 'Bathrooms' %>
    </p><br>

    <p class = "buffer5">
      <%= form.label :summary %>
      <%= form.text_field :summary, type: 'Summary' %>  
    </p><br>

    <p class = "buffer5">
      <%= form.label :address %>
      <%= form.text_field :address, type: 'Address' %>
    </p><br>

      <p class = "buffer5">
      <%= form.label :city %>
      <%= form.select :city, Listing.city, type: 'City' %>
    </p><br>


    <p class = "buffer5">
      <%= form.label :price %>
      <%= form.text_field :price, type: 'Price' %>
    </p><br>

    <p class = "buffer5">
      <%= form.label :upload_image %><br>
      <%= form.file_field :listing_image, multiple: true %><br>
    </p><br>


    <p class = "buffer5">
      <%= form.submit %>
    </p>
  </div>

  <div class="col-sm-4">
  </div>

app/views/listings/edit.html.erb
    <%= form_for @listing, remote: true do |form| %>
    <%= render partial: '/listings/form', object: form %>

    <%= form.submit %>
    <%= link_to "Listing", listings_path %>
    <% end %>

app/views/listings/index.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to 'Home', root_path %>
          </button>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to 'Create New Listing', new_listing_path %>
          </button>
          </li>
        </ul>
     	</div>
   </div>
  </nav>



<!-- this line required at beginning & end of page in order to show pagination -->

<div class="container">
	<div class="row listings">

<%= will_paginate @listings %>
<!-- iterating over @listings and printing out param content to page -->
	<div class="col-sm-8 listings">
		<% @listings.each do |listing| %>
		<%= listing.summary %><br>
		$<%= listing.price %>/night<br>
		<%= listing.listing_type %><br>
		<%= listing.home_type %><br>
			<button type="button" class="btn btn-default buffer10">
				<%= link_to 'Show', listing_path(listing) %>
			</button><br>
		<% end %>
	</div>
<!-- links to other pages -->
	<div class="col-sm-4">
	</div>
</div>
</div>
<%= will_paginate @listings %>

app/views/listings/new.html.erb
    <%= form_for @listing, remote: true do |form| %>
    <%= render partial: '/listings/form', object: form %>
    <% end %>

app/views/listings/show.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
						<%= link_to "Back to all listings", listings_path %>
					</button>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Home", root_path %>
          </button>
          </li>
        </ul>
      </div>
   </div>
  </nav>

<div class="row">
	<div class="col-sm-4">
	</div>
	<div class="col-sm-4 container-fluid text-center top-buffer well">

    <!-- Start of test carousel -->


<div id = "carousel-example-generic" class= "carousel slide" data-ride= "carousel">
    <!-- Wrapper for slides -->
  <div class="carousel-inner">
  <% @single_listing.listing_image.each do |listing_image| %>
    <div class="item">
    <%= image_tag listing_image.main.url if @single_listing.listing_image? %>
    </div>
  <!-- Controls -->
   <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
   </a>
   <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  <% end %>
</div>


  <!--end of test carousel -->

		<%= @single_listing.summary %><br>
		Address:<%= @single_listing.address %><br>
    <%= @single_listing.city %><br>
		<%= @single_listing.home_type %><br>
		<%= @single_listing.listing_type %><br>
		$<%= @single_listing.price%><br>
		Bedrooms:<%= @single_listing.bedroom %><br>
		Bathrooms:<%= @single_listing.bathroom %><br>
		Accomodates:<%= @single_listing.accommodate %><br>


    <button type="button" class="btn btn-default bottom5">
      <%= link_to "Create New Reservation", new_listing_reservation_path(@single_listing) %>
    </button><br> 


		<button type="button" class="btn btn-default bottom5">
			<%= link_to "Edit", edit_listing_path(@single_listing) %>
		</button><br>
		<button type="button" class="btn btn-default bottom5">
			<%= link_to "Delete", listing_path(@single_listing),
														:data => {:confirm => "You sure?",
                            :method => "delete"} %>
    </button><br>
		</div>

	<div class="col-sm-4">
	</div>
</div>