config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations,except: [:new, :create]
  resources :tags


  root 'homes#index'
  get 'braintree/new'
  post 'braintree/checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	validates :start_date,
           		:end_date,
            	presence: true

belongs_to :user
belongs_to :listing

# after_create :reservation_message
before_create :block_out

protected
  def block_out
    current_reservations = Reservation.where(:listing_id => self.listing_id)
    current_reservations.each do |reservation|
      if self.start_date < reservation.end_date && self.end_date > reservation.start_date && self.end_date < reservation.end_date && self.end_date > reservation.start_date
        return false
      end
    end
  end

  # def reservation_message
  #   UserMailer.reservation_confirmation(self).deliver
  # end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

#show all reservations page 
	def index
		@reservations = Reservation.all
		@user_reservations = current_user.reservations.all
	end 


#renders page to create reservation
	def new
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.new
	end 

#creates a reservation
	def create
		@listing = Listing.find(params[:reservation][:listing_id])
		@new_reservation = current_user.reservations.new(reservation_params)
		if @new_reservation.save
			@notice = 'reservation created'
			redirect_to reservations_path, :notice => @notice
		else
			@notice = 'reservation creation FAILED'
			redirect_to new_listing_reservation_path, :notice => @notice
		end
	end 

#shows a specific reservation
	def show
		@reservations = Reservation.find_by(id: params[:id]) 
	end 

	def destroy
		@single_reservation = Reservation.find_by(id: params[:id]) 
		if @single_reservation.destroy
			redirect_to reservations_path, notice: 'Reservation was successfully deleted.'
		end
	end

#update single listing within show page
	def edit
		@reservation = Reservation.find_by(id: params[:id]) 
	end

#update reservation
	def update
	@updated_reservation = current_user.reservations.find_by(id: params[:id])
	respond_to do |format|
		  if @updated_reservation.update(reservation_params)
			@notice = 'reservation updated'
			else
			@notice = 'reservation update FAILED'
			end 
			redirect_to new_reservation_path, :notice => @notice
		end 
	end 


	private
	def reservation_params
		params.require(:reservation).permit(:user_id, :listing_id, :start_date, :end_date)
	end 
end 

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Back to all listings", listings_path %>
          </button>
         
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Home", root_path %>
          </button>
          </li>
        </ul>
      </div>
   </div>
  </nav>



    <div class="row">
 <div class='col-sm-3'> <!-- empty div -->
</div>


<div class='input-group date datepicker'>
	<span class="input-group-addon">
		<span class="glyphicon glyphicon-calendar">
			<%= form.label :start_date %>
			<%= form.text_field :start_date, hide_label: true %>
		</span>
	</span>
</div>
<%= form.hidden_field :listing_id, value: @listing.id %>
<div class='input-group date datepicker'>
	<span class="input-group-addon">
		<span class="glyphicon glyphicon-calendar">
			<%= form.label :end_date %>
			<%= form.text_field :end_date, hide_label: true %>
		</span>
	</span>
</div>

<%= form.submit %>


<script type="text/javascript">
$(function () {
$('.datepicker').datetimepicker();
});
</script>




<div class='col-sm-3'> <!-- empty div -->
</div>

app/views/reservations/index.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to 'Home', root_path %>
          </button>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to 'Create New Listing', new_listing_path %>
          </button>
  
          </li>
        </ul>
     	</div>
   </div>
  </nav>


<p> My reservations </p>

  <% @user_reservations.each do |user_reservations| %>
    Check-in <%= user_reservations.start_date %><br>
    Check-out <%= user_reservations.end_date %><br>
    Listing id: <%= user_reservations.listing_id %><br>
    User id: <%= user_reservations.user_id %><br>
    <%= link_to "Make Payment", braintree_new_path %><br>
    <% end %>

app/views/reservations/new.html.erb
    <%= form_for([@listing,@reservation]) do |form| %>
    <%= render partial: '/reservations/form', object: form %>
    <% end %>

app/views/reservations/show.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
          <button type="button" class="btn btn-default buffer10">
						<%= link_to "Back to all listings", listings_path %>
					</button>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Home", root_path %>
          </button>
          </li>
        </ul>
      </div>
   </div>
  </nav>

  <div class="container">
  <div class="row reservations">


  <div class="col-sm-8 reservations">
    <% @single_listing_reservations.each do |reservation| %>
    Check-in <%= single_listing_reservation.start_date %><br>
    Check-out <%= single_listing_reservation.end_date %><br>
    <% end %>
  </div>
<!-- links to other pages -->
  <div class="col-sm-4">
  </div>
</div>
</div>