config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations,except: [:new, :create]
  resources :tags


  root 'homes#index'
  get 'braintree/new'
  post 'braintree/checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		# if logged_in, then render 'index'
		# redirect to /sign_in
	end
end

app/views/homes/index.html.erb
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
        <a class="navbar-brand $dark-color title" href="#">Wherebnb</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "Sign out", sign_out_path, method: :delete %>
          </button>
          <button type="button" class="btn btn-default buffer10">
            <%= link_to "View profile", user_path(current_user) %><br>
          </button>
          </li>
        <% end %>
        </ul>
     </div>
   </div>
  </nav>


<div class="row">
  <div class="col-sm-4"></div> <!-- empty div -->

  <div class="col-sm-4 container-fluid text-center top-buffer">
    <h1 class="title">Wherebnb</h1>
    <img src="house.png" class="img-responsive buffer5" alt="House" style="display:inline; width: 100px; height: 100px;"><br>
    <% if signed_in? %>
  	<button type="button" class="btn btn-default buffer5">
      <%= link_to 'See all listings', listings_path %></button><br>

      <button type="button" class="btn btn-default buffer5">
      <%= link_to 'Create New Listing', new_listing_path %></button><br>

      <button type="button" class="btn btn-default bottom5">
      <%= link_to "Show my reservations", reservations_path %></button><br>

      Where do you want to go? 

<%= form_tag(listings_path, :method => "get", id: "search-form") do %>
<%= select_tag "city", options_for_select(Listing.city), placeholder: "Search Listings" %>
<%= submit_tag "Search" %>
<% end %>
  
  </div>



  <div class="col-sm-4 container-fluid text-center title">
      <% else %>
	    <button type="button" class="btn btn-default buffer5">
       <%= link_to "Sign in", sign_in_path %> 
      </button><br>

      <button type="button" class="btn btn-default buffer5 first-color">
        <%= link_to "Sign up", sign_up_path %>
      </button><br>
      <button type="button" class="btn btn-default buffer5">
        <%= link_to "Sign in with Facebook", "/auth/facebook" %>
      </button><br>
	    <% end %>
	</div>
</div>